### ISSUE TITLE
I would like to fork this repo

### ISSUE THREAD

**Issue by domenicomonaco** [Holovashcenko/basic-webpack#1]
Hi man, 
i found your small boilerplate very useful as "base boilerplate". I would like to use your boilerplate as base my small project https://github.com/Tecnologie-per-Persone/GDPR-Commons-code

My goal is to have small pre-compiled html components to be used into context of "GDPR Law" as example Cookie Banners or other requirements. Obviously all open and reusable. 

if you want we can keep in contact 
thanks

**Comment by Holovashcenko** [comment]
Hi! I'm glad that my template was useful to you.
Yes, we can keep in touch.
Thank you and good luck with your project!
